### ISSUE TITLE
`tcp` is not co-linkable with `mirage-tcpip`

### ISSUE THREAD

**Issue by dinosaure** [roburio/utcp#1]
Even with `dune`, `tcp` is not co-linkable with `mirage-tcpip` when they share several names such as `Tcp__segment`. I'm not sure how to fix that in the proper way - or if we really want to fix such issue. May be one solution is to rename the project `utcp`.

**Comment by hannesm** [comment]
Hmm, I'm not sure why it should be co-linkable. OTOH, maybe indeed the top-level library name (+opam package) should be different (tcp -> utcp, as you suggested).

**Comment by hannesm** [comment]
done in https://github.com/roburio/utcp/commit/6cf6100a256caba3f3346d70bfc514aa8d371ca6
