### ISSUE TITLE
make tcp_mirage usable with ipv4 and ipv6 and ipv4v6 (using Ipaddr.V4.t / Ipaddr.V6.t / Ipaddr.t)

### ISSUE THREAD

**Issue by hannesm** [roburio/utcp#3]

**Comment by dinosaure** [comment]
Resolved by a5c9464bb75d5c8b560554de1d6b149c6496e2e1?

**Comment by hannesm** [comment]
yes indeed (and followed up patches https://github.com/hannesm/mirage/commit/34ffd59861a2dcd0261571f33a1588bc864a75ae and example https://github.com/hannesm/mirage-skeleton/tree/my-tcp).
